### ISSUE TITLE
Windows build: cannot enter command mode `:`

### ISSUE THREAD

**Issue by cpkio** [Gskartwii/teehee#10]
It seems to ignore the `:` key. I've tried bumping `crossterm` up to 0.18 (it crashed for higher versions) — no luck.

**Comment by Gskartwii** [comment]
Hey, thanks for the bug report! Which terminal emulator are you using on Windows?

**Comment by Gskartwii** [comment]
Additionally, in https://github.com/Gskartwii/teehee/commit/e0273d0d17c923786468a21d81628d7462d82574, I've upgraded the `crossterm` dependency and ported the code accordingly. Perhaps it can be helpful for fixing the issue (unfortunately I'm not able to test it right now).

**Comment by cpkio** [comment]
I'm using [ConEmu](https://github.com/Maximus5/ConEmu), but this has been tested with running from «Run» menu. _Neovim_ and _Far Manager_ are working fine, so nothing is bothering in the way. Some other keys aren't working too, but I think `:` is the most obvious to test and fixing this will fix others.

I've cloned the repo from scratch and built it — nope, still no luck, no command mode.

**Comment by Gskartwii** [comment]
My new hypothesis is that the `crossterm` interface reports the `SHIFT` key modifier differently depending on the platform. Perhaps the newest commit will fix it?

**Comment by cpkio** [comment]
Nope, didn't work. I just do `cargo install --path .` if it's relevant.

**Comment by Gskartwii** [comment]
`cargo install --path .` should be perfect, if you subsequently run the program that is located in Cargo's `bin` folder (which typically is in the `PATH`).

I've made yet another attempt to remedy the issue (the last one had a glaring flaw that I missed, sorry!) If this one doesn't fix it, I'll look into setting up ConEmu for myself for easier debugging.

The relevant commit: https://github.com/Gskartwii/teehee/commit/198932aee4556a3a8bd93f45218185a96eec0508

**Comment by cpkio** [comment]
Now it seems to work as expected 👍

**Comment by Gskartwii** [comment]
Good to hear so!
